version: '3.3'
services:
    web:
        build: 
            context: ./php
            dockerfile: Dockerfile
        container_name: php74
        depends_on: 
            - db
        volumes:
            - ./php:/var/www/html
        ports:
            - 8000:80
    db:
        container_name: mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: web_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: kagx25pass
        ports: 
            - 6033:3306
    admin:
        container_name: admin_db
        image: phpmyadmin
        depends_on: 
            - db
        ports: 
            - 3000:80
